//metadata that will show up for the about page.
export const metadata = {
  title: "About",
  description: "Generated by create next app",
};

// i think our /about/page will the wrapped around this component

const AboutLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
      <div>About Navbar</div>
      {children}
    </>
  );
};

export default AboutLayout;
